### ISSUE TITLE
Digma in vs code with docker extension

### ISSUE THREAD

**Issue by martasp** [digma-ai/digma-vscode-plugin#289]
I tried running digma-vscode-plugin with docker Digma extension  locally on [repository ](https://github.com/digma-ai/otel-sample-application-dotnet) I encountered this error :

```
[Error  - 20:36:21.287] Failed to get spans
Request failed with http code: [401] Unauthorized
Response: 
[Info  - 20:36:21.288] Scanning of opened documents started
[Info  - 20:36:21.288] Scanning of opened documents completed
[Info  - 20:36:21.289] Background scanning started
[Error  - 20:36:21.290] Failed to get environments
Error: Request failed with http code: [401] Unauthorized
Response: 
    at AnalyticsProvider.send (c:\Users\marta\.vscode\extensions\digma.digma-0.5.49\out\services\analyticsProvider.js:320:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AnalyticsProvider.getEnvironments (c:\Users\marta\.vscode\extensions\digma.digma-0.5.49\out\services\analyticsProvider.js:111:30)
    at EnvironmentManager.getEnvironments (c:\Users\marta\.vscode\extensions\digma.digma-0.5.49\out\services\EnvironmentManager.js:12:34)
    at EnvironmentManager.initializeCurrentEnvironment (c:\Users\marta\.vscode\extensions\digma.digma-0.5.49\out\services\EnvironmentManager.js:18:34)
    at activate (c:\Users\marta\.vscode\extensions\digma.digma-0.5.49\out\extension.js:52:5)
    at m.n (c:\Users\marta\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:6409)
    at m (c:\Users\marta\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:6372)
    at m.l (c:\Users\marta\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:5829)
[Error  - 20:36:22.370] Failed to get environments
Error: Request failed with http code: [401] Unauthorized
```

![image](https://github.com/user-attachments/assets/f170b100-1288-4fbd-9c90-066a70a13028)
![image](https://github.com/user-attachments/assets/beccc4e5-be67-4569-93c2-baa0fef7109e)

Do I need to register and add a token to the extension settings?
Should this scenario work for a free tier?

**Comment by doppleware** [comment]
Hey @martasp unfortunately, the Digma vscode plugin is currently not actively maintained... The reason is that we have shifted focus on the IntelliJ plugin until the UI is stabilized. Oce that happens (which is actually pretty soon) we will come back to rework on the plugin with the updated UI in place.

Sorry for the hassle! I will  add a comment in the repo as well.
